using PayrollApp.Core.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PayrollApp.Repository.Migrations
{
    internal sealed partial class Configuration : DbMigrationsConfiguration<PayrollAppDbContext>
    {
        private void SeedStates(PayrollAppDbContext context)
        {
            context.States.AddOrUpdate(x => x.StateID,
                new State() { StateID = 1, StateCode = "AB", StateName = "Alberta", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 2, StateCode = "BC", StateName = "British Columbia", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 3, StateCode = "MB", StateName = "Manitoba", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 4, StateCode = "NB", StateName = "New Brunswick", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 5, StateCode = "NT", StateName = "Northwest Territories", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 6, StateCode = "NS", StateName = "Nova Scotia", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 7, StateCode = "NU", StateName = "Nunavut", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 8, StateCode = "ON", StateName = "Ontario", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 9, StateCode = "PE", StateName = "Prince Edward Island", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 10, StateCode = "QC", StateName = "Quebec", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 11, StateCode = "SK", StateName = "Saskatchewan", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 12, StateCode = "YT", StateName = "Yukon", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 13, StateCode = "NL", StateName = "Newfoundland and Labrador", CountryID = 1, CountryCode = "CA", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 14, StateCode = "AR", StateName = "Arkansas", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 15, StateCode = "DC", StateName = "District of Columbia", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 16, StateCode = "DE", StateName = "Delaware", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 17, StateCode = "FL", StateName = "Florida", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 18, StateCode = "GA", StateName = "Georgia", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 19, StateCode = "KS", StateName = "Kansas", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 20, StateCode = "LA", StateName = "Louisiana", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 21, StateCode = "MD", StateName = "Maryland", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 22, StateCode = "MO", StateName = "Missouri", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 23, StateCode = "MS", StateName = "Mississippi", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 24, StateCode = "NC", StateName = "North Carolina", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 25, StateCode = "OK", StateName = "Oklahoma", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 26, StateCode = "SC", StateName = "South Carolina", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 27, StateCode = "TN", StateName = "Tennessee", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 28, StateCode = "TX", StateName = "Texas", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 29, StateCode = "WV", StateName = "West Virginia", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 30, StateCode = "AL", StateName = "Alabama", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 31, StateCode = "CT", StateName = "Connecticut", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 32, StateCode = "IA", StateName = "Iowa", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 33, StateCode = "IL", StateName = "Illinois", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 34, StateCode = "IN", StateName = "Indiana", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 35, StateCode = "ME", StateName = "Maine", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 36, StateCode = "MI", StateName = "Michigan", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 37, StateCode = "MN", StateName = "Minnesota", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 38, StateCode = "NE", StateName = "Nebraska", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 39, StateCode = "NH", StateName = "New Hampshire", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 40, StateCode = "NJ", StateName = "New Jersey", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 41, StateCode = "NY", StateName = "New York", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 42, StateCode = "OH", StateName = "Ohio", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 43, StateCode = "RI", StateName = "Rhode Island", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 44, StateCode = "VT", StateName = "Vermont", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 45, StateCode = "WI", StateName = "Wisconsin", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 46, StateCode = "CA", StateName = "California", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 47, StateCode = "CO", StateName = "Colorado", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 48, StateCode = "NM", StateName = "New Mexico", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 49, StateCode = "NV", StateName = "Nevada", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 50, StateCode = "UT", StateName = "Utah", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 51, StateCode = "AZ", StateName = "Arizona", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 52, StateCode = "ID", StateName = "Idaho", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 53, StateCode = "MT", StateName = "Montana", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 54, StateCode = "ND", StateName = "North Dakota", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 55, StateCode = "OR", StateName = "Oregon", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 56, StateCode = "SD", StateName = "South Dakota", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 57, StateCode = "WA", StateName = "Washington", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 58, StateCode = "WY", StateName = "Wyoming", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 59, StateCode = "HI", StateName = "Hawaii", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 60, StateCode = "AK", StateName = "Alaska", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 61, StateCode = "KY", StateName = "Kentucky", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 62, StateCode = "MA", StateName = "Massachusetts", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 63, StateCode = "PA", StateName = "Pennsylvania", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 },
                new State() { StateID = 64, StateCode = "VA", StateName = "Virginia", CountryID = 2, CountryCode = "US", SortOrder = 1, IsEnable = true, Created = DateTime.Now, LastUpdated = DateTime.Now, Remark = "-", IsDelete = false, CreatedBy = 1, LastUpdatedBy = 1 });
        }

    }
}
