SET IDENTITY_INSERT [dbo].[Customers] ON 
INSERT [dbo].[Customers] ([CustomerID], [CustomerName], [CompanyName], [AccountNo], [SalesRepID], [PaymentTermID], [RequirePO], [UniquePO], [PayByCC], [Delinquent], [InvoiceDiscountMessage], [HideCustomerName], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (2, N'Some Customer', N'Some Company', N'SOM001', 2, 5, 1, 1, 0, 0, 0, 0, 1, 1, CAST(N'2017-02-25 06:06:52.217' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[Customers] ([CustomerID], [CustomerName], [CompanyName], [AccountNo], [SalesRepID], [PaymentTermID], [RequirePO], [UniquePO], [PayByCC], [Delinquent], [InvoiceDiscountMessage], [HideCustomerName], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (3, N'Payne Transport', N'Payne Transport Ltd', N'PAY001', 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, CAST(N'2017-02-27 06:27:27.837' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[Customers] ([CustomerID], [CustomerName], [CompanyName], [AccountNo], [SalesRepID], [PaymentTermID], [RequirePO], [UniquePO], [PayByCC], [Delinquent], [InvoiceDiscountMessage], [HideCustomerName], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (4, N'Master Feeds', N'Master Feeds', N'MAS001', 3, 3, 1, 0, 0, 0, 0, 0, 1, 1, CAST(N'2017-02-28 07:07:18.770' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[Customers] ([CustomerID], [CustomerName], [CompanyName], [AccountNo], [SalesRepID], [PaymentTermID], [RequirePO], [UniquePO], [PayByCC], [Delinquent], [InvoiceDiscountMessage], [HideCustomerName], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (5, N'Jignesh Kheni', N'appstane', N'JIG001', 2, 4, 0, 1, 0, 1, 0, 1, 1, 1, CAST(N'2017-02-28 09:06:33.227' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[Customers] ([CustomerID], [CustomerName], [CompanyName], [AccountNo], [SalesRepID], [PaymentTermID], [RequirePO], [UniquePO], [PayByCC], [Delinquent], [InvoiceDiscountMessage], [HideCustomerName], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (6, N'Holz Constructors Inc', N'Holz Constructors Inc', N'HOL001', 1, 4, 1, 1, 0, 0, 0, 0, 1, 1, CAST(N'2017-03-03 07:59:22.523' AS DateTime), CAST(N'2017-03-03 08:00:37.880' AS DateTime), N'--', 0, 1, 1)
INSERT [dbo].[Customers] ([CustomerID], [CustomerName], [CompanyName], [AccountNo], [SalesRepID], [PaymentTermID], [RequirePO], [UniquePO], [PayByCC], [Delinquent], [InvoiceDiscountMessage], [HideCustomerName], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (7, N'Mat Adams', N'QuickService', N'MAT001', 2, 4, 1, 1, 1, 1, 1, 1, 1, 1, CAST(N'2017-03-07 10:42:31.540' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[Customers] ([CustomerID], [CustomerName], [CompanyName], [AccountNo], [SalesRepID], [PaymentTermID], [RequirePO], [UniquePO], [PayByCC], [Delinquent], [InvoiceDiscountMessage], [HideCustomerName], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (8, N'Mat Williams', N'QuickService', N'MAT002', 2, 4, 1, 1, 1, 0, 1, 0, 1, 1, CAST(N'2017-03-07 10:45:09.333' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[Customers] ([CustomerID], [CustomerName], [CompanyName], [AccountNo], [SalesRepID], [PaymentTermID], [RequirePO], [UniquePO], [PayByCC], [Delinquent], [InvoiceDiscountMessage], [HideCustomerName], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (9, N'William Smith', N'QuickService', N'WIL001', 4, 4, 1, 1, 1, 0, 1, 1, 1, 1, CAST(N'2017-03-07 10:49:13.223' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[Customers] ([CustomerID], [CustomerName], [CompanyName], [AccountNo], [SalesRepID], [PaymentTermID], [RequirePO], [UniquePO], [PayByCC], [Delinquent], [InvoiceDiscountMessage], [HideCustomerName], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (10, N'TEST', N'TEST', N'TES001', 2, 4, 1, 1, 0, 0, 0, 0, 1, 1, CAST(N'2017-03-07 10:03:34.907' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[Customers] ([CustomerID], [CustomerName], [CompanyName], [AccountNo], [SalesRepID], [PaymentTermID], [RequirePO], [UniquePO], [PayByCC], [Delinquent], [InvoiceDiscountMessage], [HideCustomerName], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (11, N'7 eleven', N'7 eleven', N'7EL001', 4, 3, 0, 0, 0, 0, 0, 0, 1, 1, CAST(N'2017-03-07 12:00:30.977' AS DateTime), CAST(N'2017-03-07 12:00:59.147' AS DateTime), N'--', 0, 1, 1)
INSERT [dbo].[Customers] ([CustomerID], [CustomerName], [CompanyName], [AccountNo], [SalesRepID], [PaymentTermID], [RequirePO], [UniquePO], [PayByCC], [Delinquent], [InvoiceDiscountMessage], [HideCustomerName], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (12, N'Mathieu', N'None', N'MAT003', 4, 4, 1, 1, 1, 0, 0, 0, 1, 1, CAST(N'2017-03-09 16:32:23.690' AS DateTime), NULL, N'--', 0, 1, NULL)
SET IDENTITY_INSERT [dbo].[Customers] OFF