SET IDENTITY_INSERT [dbo].[CustomerSiteJobLocations] ON 
INSERT [dbo].[CustomerSiteJobLocations] ([CustomerSiteJobLocationID], [CustomerSiteID], [JobLocation], [JobAddress], [JobNote], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (1, 1, N'First TIme', N'33 Sherbrooke', N'Be on deck', 1, 1, CAST(N'2017-02-26 18:49:28.730' AS DateTime), CAST(N'2017-02-28 05:54:03.610' AS DateTime), N'--', 0, 1, 1)
INSERT [dbo].[CustomerSiteJobLocations] ([CustomerSiteJobLocationID], [CustomerSiteID], [JobLocation], [JobAddress], [JobNote], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (2, 2, NULL, NULL, NULL, 1, 1, CAST(N'2017-02-27 06:30:33.487' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[CustomerSiteJobLocations] ([CustomerSiteJobLocationID], [CustomerSiteID], [JobLocation], [JobAddress], [JobNote], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (3, 2, N'Sobeys Warehouse', N'1800 Inkster Blvd.', NULL, 1, 1, CAST(N'2017-02-27 06:34:42.447' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[CustomerSiteJobLocations] ([CustomerSiteJobLocationID], [CustomerSiteID], [JobLocation], [JobAddress], [JobNote], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (4, 3, NULL, NULL, NULL, 1, 1, CAST(N'2017-02-28 07:22:22.530' AS DateTime), CAST(N'2017-03-02 10:33:57.347' AS DateTime), N'--', 0, 1, 1)
INSERT [dbo].[CustomerSiteJobLocations] ([CustomerSiteJobLocationID], [CustomerSiteID], [JobLocation], [JobAddress], [JobNote], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (5, 4, NULL, NULL, NULL, 1, 1, CAST(N'2017-03-02 10:33:04.613' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[CustomerSiteJobLocations] ([CustomerSiteJobLocationID], [CustomerSiteID], [JobLocation], [JobAddress], [JobNote], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (6, 5, N'123 Adelaide', N'123 Adelaide', N'Digging Trench', 1, 1, CAST(N'2017-03-03 08:25:25.873' AS DateTime), CAST(N'2017-03-15 20:06:50.543' AS DateTime), N'--', 0, 1, 1)
INSERT [dbo].[CustomerSiteJobLocations] ([CustomerSiteJobLocationID], [CustomerSiteID], [JobLocation], [JobAddress], [JobNote], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (7, 10, N'New one', N'AA', N'BB', 1, 1, CAST(N'2017-03-07 12:08:49.477' AS DateTime), CAST(N'2017-03-12 19:35:58.750' AS DateTime), N'--', 0, 1, 1)
INSERT [dbo].[CustomerSiteJobLocations] ([CustomerSiteJobLocationID], [CustomerSiteID], [JobLocation], [JobAddress], [JobNote], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (8, 4, N'Hello', N'HYU', N'HYU', 1, 1, CAST(N'2017-03-12 01:31:52.937' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[CustomerSiteJobLocations] ([CustomerSiteJobLocationID], [CustomerSiteID], [JobLocation], [JobAddress], [JobNote], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (9, 7, N'test', N'Test addr', N'Test note', 1, 1, CAST(N'2017-03-13 07:09:13.747' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[CustomerSiteJobLocations] ([CustomerSiteJobLocationID], [CustomerSiteID], [JobLocation], [JobAddress], [JobNote], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (10009, 8, N'New York', N'New York', N'Some note', 1, 1, CAST(N'2017-03-15 07:54:43.117' AS DateTime), NULL, N'--', 0, 1, NULL)
SET IDENTITY_INSERT [dbo].[CustomerSiteJobLocations] OFF
