SET IDENTITY_INSERT [dbo].[EmployeeCertifications] ON 
INSERT [dbo].[EmployeeCertifications] ([EmployeeCertificationID], [EmployeeID], [CertificationID], [Picture], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (1, 2, 6, NULL, 1, 1, CAST(N'2017-02-25 06:04:14.333' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeCertifications] ([EmployeeCertificationID], [EmployeeID], [CertificationID], [Picture], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (2, 2, 4, NULL, 1, 1, CAST(N'2017-02-25 06:04:27.257' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeCertifications] ([EmployeeCertificationID], [EmployeeID], [CertificationID], [Picture], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (3, 2, 7, NULL, 1, 1, CAST(N'2017-02-25 06:04:28.850' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeCertifications] ([EmployeeCertificationID], [EmployeeID], [CertificationID], [Picture], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (4, 4, 11, NULL, 1, 1, CAST(N'2017-03-07 12:06:31.013' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeCertifications] ([EmployeeCertificationID], [EmployeeID], [CertificationID], [Picture], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (5, 7, 1, NULL, 1, 1, CAST(N'2017-03-11 13:27:16.683' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeCertifications] ([EmployeeCertificationID], [EmployeeID], [CertificationID], [Picture], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (6, 4, 1, NULL, 1, 1, CAST(N'2017-03-12 11:44:27.307' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeCertifications] ([EmployeeCertificationID], [EmployeeID], [CertificationID], [Picture], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (7, 4, 2, NULL, 1, 1, CAST(N'2017-03-12 11:44:50.863' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeCertifications] ([EmployeeCertificationID], [EmployeeID], [CertificationID], [Picture], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (8, 4, 3, NULL, 1, 1, CAST(N'2017-03-12 11:51:29.093' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeCertifications] ([EmployeeCertificationID], [EmployeeID], [CertificationID], [Picture], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (9, 4, 6, NULL, 1, 1, CAST(N'2017-03-13 08:39:36.040' AS DateTime), CAST(N'2017-03-13 08:39:40.023' AS DateTime), N'--', 1, 1, 1)
INSERT [dbo].[EmployeeCertifications] ([EmployeeCertificationID], [EmployeeID], [CertificationID], [Picture], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (10009, 4, 6, NULL, 1, 1, CAST(N'2017-03-15 22:27:01.013' AS DateTime), NULL, N'--', 0, 1, NULL)
SET IDENTITY_INSERT [dbo].[EmployeeCertifications] OFF
