SET IDENTITY_INSERT [dbo].[EmployeeSkills] ON 
INSERT [dbo].[EmployeeSkills] ([EmployeeSkillID], [EmployeeID], [SkillID], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (1, 2, 1, 1, 1, CAST(N'2017-02-25 06:04:20.303' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeSkills] ([EmployeeSkillID], [EmployeeID], [SkillID], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (2, 2, 9, 1, 1, CAST(N'2017-02-25 06:04:21.787' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeSkills] ([EmployeeSkillID], [EmployeeID], [SkillID], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (3, 2, 7, 1, 1, CAST(N'2017-02-25 06:04:44.037' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeSkills] ([EmployeeSkillID], [EmployeeID], [SkillID], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (4, 2, 11, 1, 1, CAST(N'2017-02-25 06:04:45.270' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeSkills] ([EmployeeSkillID], [EmployeeID], [SkillID], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (5, 4, 7, 1, 1, CAST(N'2017-03-07 12:06:52.153' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeSkills] ([EmployeeSkillID], [EmployeeID], [SkillID], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (6, 4, 9, 1, 1, CAST(N'2017-03-12 21:47:53.567' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeSkills] ([EmployeeSkillID], [EmployeeID], [SkillID], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (7, 4, 11, 1, 1, CAST(N'2017-03-12 21:47:57.043' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeSkills] ([EmployeeSkillID], [EmployeeID], [SkillID], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (8, 4, 3, 1, 1, CAST(N'2017-03-12 21:48:01.010' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeSkills] ([EmployeeSkillID], [EmployeeID], [SkillID], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (9, 4, 2, 1, 1, CAST(N'2017-03-15 22:27:06.700' AS DateTime), NULL, N'--', 0, 1, NULL)
SET IDENTITY_INSERT [dbo].[EmployeeSkills] OFF