
SET IDENTITY_INSERT [dbo].[EmployeeLabourClassifications] ON 
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (1, 2, 1, 0, CAST(12.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-02-25 06:04:01.413' AS DateTime), CAST(N'2017-02-25 06:04:08.977' AS DateTime), N'--', 0, 1, 1)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (2, 2, 3, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-02-25 06:04:33.787' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (3, 2, 4, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-02-25 06:04:35.007' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (4, 2, 5, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-02-25 06:04:36.880' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (5, 3, 15, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-02-27 06:10:48.250' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (6, 4, 2, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-02-28 07:29:36.797' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (7, 4, 1, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-02-28 07:29:39.437' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (8, 4, 15, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-02-28 07:29:44.997' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (9, 4, 9, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-02-28 07:29:49.967' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (10, 7, 1, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-03-06 09:46:46.583' AS DateTime), CAST(N'2017-03-06 09:47:29.973' AS DateTime), N'--', 1, 1, 1)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (11, 7, 2, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-03-06 09:47:09.503' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (12, 7, 3, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-03-06 09:48:01.783' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (13, 4, 3, 0, CAST(11.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-03-07 12:06:16.183' AS DateTime), NULL, N'--', 0, 1, NULL)
INSERT [dbo].[EmployeeLabourClassifications] ([EmployeeLabourClassificationID], [EmployeeID], [LabourClassificationID], [IsExpire], [Rate], [SortOrder], [IsEnable], [Created], [LastUpdated], [Remark], [IsDelete], [CreatedBy], [LastUpdatedBy]) VALUES (14, 4, 4, 0, CAST(9.00 AS Decimal(18, 2)), 1, 1, CAST(N'2017-03-12 11:44:02.363' AS DateTime), CAST(N'2017-03-15 20:17:23.290' AS DateTime), N'--', 0, 1, 1)
SET IDENTITY_INSERT [dbo].[EmployeeLabourClassifications] OFF